# Generated by Django 4.2.5 on 2023-10-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_todos_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
